#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
0 -> 0xd00 program
0xd00 -> 0xf00 stack
0xf00 -> 0xf02 pc
0xf02 -> 0xf04 sp
*/

enum Register { R0 = 0, R1, R2, R3, R4, R5, R6, R7, REGISTER_NUM };
#define STACK_ADDR 0xd00
#define PC_ADDR 0xf00
#define SP_ADDR 0xf02

struct vm {
  uint16_t pc;
  uint8_t mem[0x1000];
  uint8_t program[0x800];
  uint16_t regs[REGISTER_NUM];
  uint8_t eq_flag;
};

typedef struct vm *vm_t;
typedef void (*handler_t)(vm_t, uint16_t instr);

#if 0
#define DEBUG(...) printf(__VA_ARGS__)
#else
#define DEBUG(...)
#endif

void ld_imm(vm_t vm, uint16_t instr) {
  DEBUG("LD %x\n", instr & 0xfff);
  vm->regs[R0] = instr & 0xfff;
}

void ld_rel(vm_t vm, uint16_t instr) {
  DEBUG("LD R%d, [R%d]\n", instr >> 8 & 0xf, instr & 0xf);
  uint16_t value = (vm->mem[vm->regs[instr & 0xf] + 1] << 8) |
                   vm->mem[vm->regs[instr & 0xf]];
  vm->regs[instr >> 8 & 0xf] = value;
}

void ld_reg(vm_t vm, uint16_t instr) {
  DEBUG("LD R%d (%x)\n", instr >> 8 & 0xf, vm->regs[instr & 0xf]);
  vm->regs[instr >> 8 & 0xf] = vm->regs[instr & 0xf];
}

void st(vm_t vm, uint16_t instr) {
  DEBUG("ST [%x]\n", instr & 0xfff);
  uint16_t value = vm->regs[R0];
  vm->mem[instr & 0xfff] = value & 0xff;
  vm->mem[(instr & 0xfff) + 1] = value >> 8;
}

void add(vm_t vm, uint16_t instr) {
  DEBUG("ADD R%d, R%d\n", instr >> 8 & 0xf, instr & 0xf);
  vm->regs[instr >> 8 & 0xf] += vm->regs[instr & 0xf];
}

void xor
    (vm_t vm, uint16_t instr) {
      DEBUG("XOR R%d, R%d (%x ^ %x)\n", instr >> 8 & 0xf, instr & 0xf,
            vm->regs[instr >> 8 & 0xf], vm->regs[instr & 0xf]);
      vm->regs[instr >> 8 & 0xf] ^= vm->regs[instr & 0xf];
    }

    void cmp(vm_t vm, uint16_t instr) {
  DEBUG("CMP R%d, R%d", instr >> 8 & 0xf, instr & 0xf);
  uint8_t val1 = vm->regs[instr >> 8 & 0xf];
  uint8_t val2 = vm->regs[instr & 0xf];
  vm->eq_flag = val1 == val2;
}

void jmp(vm_t vm, uint16_t instr) {
  DEBUG("JMP %x\n", instr & 0xfff);
  uint16_t saved_pc = vm->pc;
  vm->pc = vm->regs[instr & 0xf];
  vm->regs[R7] = saved_pc;
}

void je(vm_t vm, uint16_t instr) {
  DEBUG("JE %x\n", instr & 0xfff);
  if (vm->eq_flag) {
    uint16_t saved_pc = vm->pc;
    vm->pc = vm->regs[instr & 0xf];
    vm->regs[R7] = saved_pc;
  }
}

void getch(vm_t vm, uint16_t instr) {
  DEBUG("GETCH R%d\n", instr & 0xf);
  uint8_t value = getchar();
  vm->regs[instr & 0xf] = value;
}

void putch(vm_t vm, uint16_t instr) {
  DEBUG("PUTCH R%d\n", instr & 0xf);
  putchar(vm->regs[instr & 0xf]);
}

void leave(vm_t vm, uint16_t instr) {
  DEBUG("LEAVE\n");
  exit(0);
}
void sub(vm_t vm, uint16_t instr) {
  DEBUG("ADD R%d, R%d", instr >> 8 & 0xf, instr & 0xf);
  vm->regs[instr >> 8 & 0xf] -= vm->regs[instr & 0xf];
}

void st_rel(vm_t vm, uint16_t instr) {
  vm->mem[vm->regs[instr >> 8 & 0xf]] = vm->regs[instr & 0xf] & 0xff;
}

void shr(vm_t vm, uint16_t instr) {
  vm->regs[instr >> 8 & 0xf] >>= vm->regs[instr & 0xff];
}
void and (vm_t vm, uint16_t instr) {
  DEBUG("AND R%d, R%d (%x ^ %x)\n", instr >> 8 & 0xf, instr & 0xf,
        vm->regs[instr >> 8 & 0xf], vm->regs[instr & 0xf]);
  vm->regs[instr >> 8 & 0xf] &= vm->regs[instr & 0xf];
}

handler_t handlers[] = {ld_imm, ld_rel, ld_reg, st,  add,   xor,    cmp, jmp,
                        je,     getch,  putch,  sub, leave, st_rel, shr, and};

#define LDIMM(x) ((0 << 12) | x)
#define LDREL(x, y) ((1 << 12) | (x << 8) | y)
#define LDREG(x, y) ((2 << 12) | (x << 8) | y)
#define ST(x) ((3 << 12) | x)
#define ADD(x, y) ((4 << 12) | (x << 8) | y)
#define XOR(x, y) ((5 << 12) | (x << 8) | y)
#define CMP(x, y) ((6 << 12) | (x << 8) | y)
#define JMP(x) ((7 << 12) | x)
#define JE(x) ((8 << 12) | x)
#define GETCH(x) ((9 << 12) | x)
#define PUTCH(x) ((10 << 12) | x)
#define SUB(x, y) ((11 << 12) | (x << 8) | y)
#define LEAVE() (12 << 12)
#define STREL(x, y) ((13 << 12) | (x << 8) | y)
#define SHR(x, y) ((14 << 12) | (x << 8) | y)
#define AND(x, y) ((15 << 12) | (x << 8) | y)

/*
 * [ x x x x | x x x x x x x x x x x x ]
 * [   OP    |       REG/IMM/MEM       ]
 *
 * 0nnn: LD R0, nnn
 * 1x0y: LD Rx, [Ry]
 * 2x0y: LD Rx, Ry
 * 3nnn: ST [nnn], R0
 * 4x0y: ADD Rx, Ry
 * 5x0y: XOR Rx, Ry
 * 6x0y: CMP Rx, Ry
 * 700x: JMP Rx
 * 800x: JE Rx
 * 900x: GETCH Rx
 * A00x: PUTCH Rx
 * B00x: SUB Rx, Ry
 * C000: LEAVE
 * Dx0y: ST [Rx], Ry
 * Exnn: SHR Rx, nn
 * Fx0y: AND Rx, Ry
 */

/*
 * 00nn: PUSH nn
 * 01nn: POP
 * 0200: ADD
 * 0300: SUB
 * 0400: XOR
 * 0500: GETCH
 * 0600: PUTCH
 * 0700: OR
 * 0800: ASSERT = 0
 */

enum Opcode {
  OP_PUSH = 0,
  OP_POP,
  OP_ADD,
  OP_SUB,
  OP_XOR,
  OP_GETCH,
  OP_PUTCH,
  OP_OR, // We don't have OR in the first VM so we make it with XOR and AND lmao
  OP_ASSERT
};

#define push_r1 (50 * 2)
#define pop_r1 (65 * 2)
#define handle_push (85 * 2)
#define handle_pop (91 * 2)
#define handle_add (95 * 2)
#define handle_sub (105 * 2)
#define handle_xor (116 * 2)
#define handle_getch (126 * 2)
#define handle_putch (131 * 2)
#define handle_or (136 * 2)
#define handle_assert (149 * 2)
#define success_br (162 * 2)

uint16_t program[] = {LDIMM(2),
                      LDREG(R2, R0),
                      LDIMM(PC_ADDR),
                      LDREL(R0, R0),
                      LDREL(R0, R0),
                      LDREG(R1, R0),
                      LDIMM(PC_ADDR),
                      LDREL(R0, R0),
                      ADD(R0, R2),
                      ST(PC_ADDR),
                      LDREG(R3, R1),
                      LDIMM(0xff),
                      AND(R3, R0),
                      LDIMM(OP_PUSH),
                      CMP(R3, R0),
                      LDIMM(handle_push),
                      JE(0),
                      LDIMM(OP_POP),
                      CMP(R3, R0),
                      LDIMM(handle_pop),
                      JE(0),
                      LDIMM(OP_ADD),
                      CMP(R3, R0),
                      LDIMM(handle_add),
                      JE(0),
                      LDIMM(OP_SUB),
                      CMP(R3, R0),
                      LDIMM(handle_sub),
                      JE(0),
                      LDIMM(OP_XOR),
                      CMP(R3, R0),
                      LDIMM(handle_xor),
                      JE(0),
                      LDIMM(OP_GETCH),
                      CMP(R3, R0),
                      LDIMM(handle_getch),
                      JE(0),
                      LDIMM(OP_PUTCH),
                      CMP(R3, R0),
                      LDIMM(handle_putch),
                      JE(0),
                      LDIMM(OP_OR),
                      CMP(R3, R0),
                      LDIMM(handle_or),
                      JE(0),
                      LDIMM(OP_ASSERT),
                      CMP(R3, R0),
                      LDIMM(handle_assert),
                      JE(0),
                      LEAVE(),
                      /* push_r1: */ LDIMM(SP_ADDR),
                      LDREL(R3, R0),
                      LDIMM(STACK_ADDR),
                      ADD(R0, R3),
                      STREL(R0, R1),
                      LDIMM(1),
                      ADD(R3, R0),
                      LDIMM(SP_ADDR),
                      STREL(R0, R3),
                      LDIMM(SP_ADDR + 1),
                      LDREG(R1, R0),
                      LDIMM(8),
                      SHR(R3, R0),
                      STREL(R1, R3),
                      JMP(R7),
                      /* pop_r1: */ LDIMM(SP_ADDR),
                      LDREL(R3, R0),
                      LDIMM(1),
                      SUB(R3, R0),
                      LDREG(R4, R3),
                      LDIMM(STACK_ADDR),
                      ADD(R3, R0),
                      LDREL(R1, R3),
                      LDIMM(0xff),
                      AND(R1, R0),
                      LDIMM(SP_ADDR),
                      STREL(R0, R4),
                      LDREG(R3, R0),
                      LDIMM(8),
                      SHR(R4, R0),
                      LDIMM(1),
                      ADD(R3, R0),
                      STREL(R3, R4),
                      LDIMM(0),
                      JMP(R7),
                      /* handle_push: */ LDIMM(8),
                      SHR(R1, R0),
                      LDIMM(push_r1),
                      JMP(R0),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_pop: */ LDIMM(pop_r1),
                      JMP(R0),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_add: */ LDIMM(pop_r1),
                      JMP(R0),
                      LDREG(R6, R1),
                      LDIMM(pop_r1),
                      JMP(R0),
                      ADD(R1, R6),
                      LDIMM(push_r1),
                      JMP(R0),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_sub: */ LDIMM(pop_r1),
                      JMP(R0),
                      LDREG(R6, R1),
                      LDIMM(pop_r1),
                      JMP(R0),
                      SUB(R6, R1),
                      LDREG(R1, R6),
                      LDIMM(push_r1),
                      JMP(R0),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_xor: */ LDIMM(pop_r1),
                      JMP(R0),
                      LDREG(R6, R1),
                      LDIMM(pop_r1),
                      JMP(R0),
                      XOR(R1, R6),
                      LDIMM(push_r1),
                      JMP(R0),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_getch: */ GETCH(R1),
                      LDIMM(push_r1),
                      JMP(R0),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_putch: */ LDIMM(pop_r1),
                      JMP(R0),
                      PUTCH(R1),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_or: */ LDIMM(pop_r1),
                      JMP(R0),
                      LDREG(R6, R1),
                      LDIMM(pop_r1),
                      JMP(R0),
                      LDREG(R5, R1),
                      AND(R5, R6),
                      XOR(R1, R6),
                      XOR(R1, R5),
                      LDIMM(push_r1),
                      JMP(R0),
                      LDIMM(0),
                      JMP(R0),
                      /* handle_assert: */ LDIMM(pop_r1),
                      JMP(R0),
                      LDIMM(0),
                      CMP(R1, R0),
                      LDIMM(success_br),
                      JE(R0),
                      LDIMM('N'),
                      PUTCH(R0),
                      LDIMM('O'),
                      PUTCH(R0),
                      LDIMM('\n'),
                      PUTCH(R0),
                      LEAVE(),
                      /* success_br: */ LDIMM('Y'),
                      PUTCH(R0),
                      LDIMM('E'),
                      PUTCH(R0),
                      LDIMM('S'),
                      PUTCH(R0),
                      LDIMM('\n'),
                      PUTCH(R0),
                      LEAVE()};

#define VM_PUSH(x) (((x) << 8) | OP_PUSH)

uint16_t vm_program[] = {VM_PUSH(0),
                         VM_PUSH(36),
                         VM_PUSH(21),
                         VM_PUSH(214),
                         VM_PUSH(53),
                         VM_PUSH(51),
                         VM_PUSH(177),
                         OP_GETCH,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(191),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(58),
                         VM_PUSH(192),
                         VM_PUSH(79),
                         VM_PUSH(96),
                         VM_PUSH(25),
                         VM_PUSH(11),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(55),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(42),
                         VM_PUSH(18),
                         VM_PUSH(104),
                         VM_PUSH(110),
                         VM_PUSH(191),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(230),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(222),
                         VM_PUSH(161),
                         VM_PUSH(184),
                         VM_PUSH(25),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(9),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(211),
                         VM_PUSH(100),
                         VM_PUSH(166),
                         VM_PUSH(93),
                         VM_PUSH(41),
                         VM_PUSH(13),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_ADD,
                         VM_PUSH(244),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(28),
                         VM_PUSH(171),
                         VM_PUSH(2),
                         VM_PUSH(197),
                         VM_PUSH(251),
                         VM_PUSH(41),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(199),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(225),
                         VM_PUSH(234),
                         VM_PUSH(131),
                         VM_PUSH(165),
                         VM_PUSH(39),
                         VM_PUSH(89),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(138),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(2),
                         VM_PUSH(202),
                         VM_PUSH(20),
                         VM_PUSH(163),
                         VM_PUSH(246),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_ADD,
                         VM_PUSH(30),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(80),
                         VM_PUSH(193),
                         VM_PUSH(233),
                         VM_PUSH(73),
                         VM_PUSH(254),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(210),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(229),
                         VM_PUSH(215),
                         VM_PUSH(124),
                         VM_PUSH(5),
                         VM_PUSH(170),
                         VM_PUSH(193),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(245),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(232),
                         VM_PUSH(229),
                         VM_PUSH(144),
                         VM_PUSH(25),
                         VM_PUSH(199),
                         VM_PUSH(66),
                         VM_PUSH(231),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(215),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(174),
                         VM_PUSH(115),
                         VM_PUSH(194),
                         VM_PUSH(121),
                         VM_PUSH(19),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(30),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(12),
                         VM_PUSH(225),
                         VM_PUSH(205),
                         VM_PUSH(58),
                         VM_PUSH(248),
                         VM_PUSH(199),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(134),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(91),
                         VM_PUSH(250),
                         VM_PUSH(5),
                         VM_PUSH(229),
                         VM_PUSH(48),
                         VM_PUSH(34),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         VM_PUSH(51),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(20),
                         VM_PUSH(32),
                         VM_PUSH(185),
                         VM_PUSH(93),
                         VM_PUSH(148),
                         VM_PUSH(226),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(77),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(52),
                         VM_PUSH(55),
                         VM_PUSH(247),
                         VM_PUSH(91),
                         VM_PUSH(21),
                         VM_PUSH(109),
                         OP_GETCH,
                         OP_SUB,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(104),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(217),
                         VM_PUSH(41),
                         VM_PUSH(211),
                         VM_PUSH(230),
                         VM_PUSH(113),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(140),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(100),
                         VM_PUSH(64),
                         VM_PUSH(150),
                         VM_PUSH(102),
                         VM_PUSH(7),
                         VM_PUSH(69),
                         VM_PUSH(139),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         VM_PUSH(183),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(211),
                         VM_PUSH(128),
                         VM_PUSH(250),
                         VM_PUSH(83),
                         VM_PUSH(104),
                         VM_PUSH(156),
                         VM_PUSH(213),
                         VM_PUSH(29),
                         OP_GETCH,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(101),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(30),
                         VM_PUSH(221),
                         VM_PUSH(161),
                         VM_PUSH(137),
                         VM_PUSH(87),
                         VM_PUSH(97),
                         VM_PUSH(128),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         VM_PUSH(208),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(106),
                         VM_PUSH(73),
                         VM_PUSH(68),
                         VM_PUSH(214),
                         VM_PUSH(211),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(209),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(210),
                         VM_PUSH(145),
                         VM_PUSH(218),
                         VM_PUSH(141),
                         VM_PUSH(94),
                         VM_PUSH(222),
                         VM_PUSH(95),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(102),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(24),
                         VM_PUSH(70),
                         VM_PUSH(83),
                         VM_PUSH(65),
                         VM_PUSH(246),
                         VM_PUSH(0),
                         VM_PUSH(62),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(16),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(121),
                         VM_PUSH(118),
                         VM_PUSH(228),
                         VM_PUSH(170),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(248),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(233),
                         VM_PUSH(221),
                         VM_PUSH(193),
                         VM_PUSH(188),
                         VM_PUSH(117),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(144),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(156),
                         VM_PUSH(73),
                         VM_PUSH(133),
                         VM_PUSH(199),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(211),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(43),
                         VM_PUSH(11),
                         VM_PUSH(222),
                         VM_PUSH(154),
                         VM_PUSH(124),
                         VM_PUSH(58),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(129),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(234),
                         VM_PUSH(224),
                         VM_PUSH(89),
                         VM_PUSH(216),
                         VM_PUSH(48),
                         VM_PUSH(246),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(35),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(223),
                         VM_PUSH(216),
                         VM_PUSH(189),
                         VM_PUSH(8),
                         VM_PUSH(199),
                         VM_PUSH(153),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(213),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(182),
                         VM_PUSH(255),
                         VM_PUSH(246),
                         VM_PUSH(17),
                         VM_PUSH(38),
                         VM_PUSH(6),
                         VM_PUSH(30),
                         VM_PUSH(80),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         VM_PUSH(167),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(229),
                         VM_PUSH(93),
                         VM_PUSH(34),
                         VM_PUSH(146),
                         VM_PUSH(185),
                         VM_PUSH(218),
                         VM_PUSH(255),
                         OP_GETCH,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(3),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(224),
                         VM_PUSH(89),
                         VM_PUSH(97),
                         VM_PUSH(111),
                         VM_PUSH(163),
                         VM_PUSH(65),
                         VM_PUSH(208),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(106),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(57),
                         VM_PUSH(208),
                         VM_PUSH(14),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(102),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(238),
                         VM_PUSH(187),
                         VM_PUSH(185),
                         VM_PUSH(6),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(97),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(97),
                         VM_PUSH(90),
                         VM_PUSH(210),
                         VM_PUSH(217),
                         VM_PUSH(127),
                         VM_PUSH(63),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(37),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(27),
                         VM_PUSH(143),
                         VM_PUSH(233),
                         VM_PUSH(73),
                         VM_PUSH(79),
                         VM_PUSH(97),
                         VM_PUSH(142),
                         VM_PUSH(16),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         VM_PUSH(119),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(117),
                         VM_PUSH(25),
                         VM_PUSH(147),
                         VM_PUSH(81),
                         VM_PUSH(113),
                         VM_PUSH(51),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(5),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(164),
                         VM_PUSH(147),
                         VM_PUSH(83),
                         VM_PUSH(147),
                         VM_PUSH(49),
                         VM_PUSH(149),
                         VM_PUSH(60),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(65),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(103),
                         VM_PUSH(95),
                         VM_PUSH(90),
                         VM_PUSH(183),
                         VM_PUSH(120),
                         VM_PUSH(78),
                         OP_GETCH,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(42),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(41),
                         VM_PUSH(93),
                         VM_PUSH(130),
                         VM_PUSH(251),
                         VM_PUSH(208),
                         VM_PUSH(89),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         VM_PUSH(49),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(89),
                         VM_PUSH(210),
                         VM_PUSH(32),
                         VM_PUSH(56),
                         VM_PUSH(237),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         VM_PUSH(224),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(111),
                         VM_PUSH(94),
                         VM_PUSH(99),
                         VM_PUSH(124),
                         VM_PUSH(65),
                         VM_PUSH(83),
                         VM_PUSH(221),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(106),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(120),
                         VM_PUSH(202),
                         VM_PUSH(129),
                         VM_PUSH(37),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(31),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(191),
                         VM_PUSH(155),
                         VM_PUSH(50),
                         VM_PUSH(48),
                         VM_PUSH(241),
                         VM_PUSH(92),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         VM_PUSH(183),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(16),
                         VM_PUSH(193),
                         VM_PUSH(26),
                         VM_PUSH(35),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(142),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(3),
                         VM_PUSH(255),
                         VM_PUSH(149),
                         OP_GETCH,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(220),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(44),
                         VM_PUSH(62),
                         VM_PUSH(129),
                         VM_PUSH(1),
                         VM_PUSH(111),
                         VM_PUSH(155),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         VM_PUSH(76),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(65),
                         VM_PUSH(251),
                         VM_PUSH(114),
                         VM_PUSH(115),
                         VM_PUSH(138),
                         VM_PUSH(74),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(136),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(121),
                         VM_PUSH(229),
                         VM_PUSH(177),
                         VM_PUSH(131),
                         VM_PUSH(145),
                         VM_PUSH(213),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(232),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(177),
                         VM_PUSH(183),
                         VM_PUSH(141),
                         VM_PUSH(84),
                         VM_PUSH(186),
                         VM_PUSH(122),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(125),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(58),
                         VM_PUSH(61),
                         VM_PUSH(141),
                         VM_PUSH(67),
                         VM_PUSH(176),
                         VM_PUSH(197),
                         VM_PUSH(16),
                         VM_PUSH(232),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         VM_PUSH(83),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(42),
                         VM_PUSH(12),
                         VM_PUSH(70),
                         VM_PUSH(15),
                         VM_PUSH(41),
                         VM_PUSH(19),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(83),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(117),
                         VM_PUSH(104),
                         VM_PUSH(230),
                         VM_PUSH(239),
                         VM_PUSH(88),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(27),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(54),
                         VM_PUSH(30),
                         VM_PUSH(145),
                         VM_PUSH(217),
                         VM_PUSH(138),
                         VM_PUSH(231),
                         OP_GETCH,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         VM_PUSH(6),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(139),
                         VM_PUSH(212),
                         VM_PUSH(40),
                         VM_PUSH(1),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(215),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(111),
                         VM_PUSH(187),
                         VM_PUSH(31),
                         VM_PUSH(3),
                         VM_PUSH(248),
                         VM_PUSH(220),
                         VM_PUSH(54),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         VM_PUSH(134),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(147),
                         VM_PUSH(123),
                         VM_PUSH(0),
                         VM_PUSH(193),
                         VM_PUSH(226),
                         VM_PUSH(213),
                         VM_PUSH(130),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         VM_PUSH(150),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(235),
                         VM_PUSH(147),
                         VM_PUSH(21),
                         VM_PUSH(133),
                         VM_PUSH(124),
                         VM_PUSH(104),
                         VM_PUSH(240),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         OP_XOR,
                         VM_PUSH(127),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(210),
                         VM_PUSH(247),
                         VM_PUSH(69),
                         VM_PUSH(87),
                         VM_PUSH(228),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_ADD,
                         OP_ADD,
                         VM_PUSH(135),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(118),
                         VM_PUSH(9),
                         VM_PUSH(125),
                         VM_PUSH(146),
                         VM_PUSH(132),
                         VM_PUSH(101),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         VM_PUSH(184),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(208),
                         VM_PUSH(184),
                         OP_GETCH,
                         OP_XOR,
                         OP_ADD,
                         VM_PUSH(183),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(121),
                         VM_PUSH(198),
                         VM_PUSH(160),
                         VM_PUSH(184),
                         VM_PUSH(15),
                         VM_PUSH(96),
                         VM_PUSH(245),
                         OP_GETCH,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         VM_PUSH(10),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(221),
                         VM_PUSH(10),
                         VM_PUSH(249),
                         VM_PUSH(42),
                         VM_PUSH(58),
                         VM_PUSH(208),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         VM_PUSH(76),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(168),
                         VM_PUSH(155),
                         VM_PUSH(70),
                         VM_PUSH(163),
                         VM_PUSH(66),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(175),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(47),
                         VM_PUSH(126),
                         VM_PUSH(168),
                         VM_PUSH(255),
                         VM_PUSH(223),
                         VM_PUSH(234),
                         VM_PUSH(43),
                         VM_PUSH(132),
                         OP_GETCH,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(102),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(236),
                         VM_PUSH(45),
                         VM_PUSH(228),
                         VM_PUSH(213),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(98),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(139),
                         VM_PUSH(132),
                         VM_PUSH(234),
                         VM_PUSH(80),
                         VM_PUSH(251),
                         VM_PUSH(54),
                         OP_GETCH,
                         OP_XOR,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(239),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(248),
                         VM_PUSH(49),
                         VM_PUSH(6),
                         VM_PUSH(106),
                         VM_PUSH(230),
                         OP_GETCH,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         VM_PUSH(200),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(119),
                         VM_PUSH(42),
                         VM_PUSH(3),
                         VM_PUSH(80),
                         VM_PUSH(31),
                         VM_PUSH(148),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_ADD,
                         OP_ADD,
                         OP_ADD,
                         OP_XOR,
                         VM_PUSH(17),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(202),
                         VM_PUSH(200),
                         VM_PUSH(220),
                         VM_PUSH(203),
                         VM_PUSH(70),
                         OP_GETCH,
                         OP_ADD,
                         OP_XOR,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         VM_PUSH(148),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(218),
                         VM_PUSH(225),
                         VM_PUSH(61),
                         VM_PUSH(125),
                         VM_PUSH(245),
                         VM_PUSH(42),
                         OP_GETCH,
                         OP_XOR,
                         OP_ADD,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         OP_SUB,
                         VM_PUSH(137),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(191),
                         VM_PUSH(235),
                         VM_PUSH(225),
                         VM_PUSH(113),
                         VM_PUSH(109),
                         VM_PUSH(183),
                         VM_PUSH(24),
                         OP_GETCH,
                         OP_ADD,
                         OP_SUB,
                         OP_SUB,
                         OP_XOR,
                         OP_SUB,
                         OP_XOR,
                         OP_XOR,
                         VM_PUSH(19),
                         OP_XOR,
                         OP_OR,
                         VM_PUSH(168),
                         VM_PUSH(225),
                         VM_PUSH(64),
                         VM_PUSH(161),
                         VM_PUSH(218),
                         VM_PUSH(88),
                         OP_GETCH,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_SUB,
                         OP_ADD,
                         OP_SUB,
                         VM_PUSH(163),
                         OP_XOR,
                         OP_OR,
                         OP_ASSERT

};

int main(int argc, char *argv[]) {
  vm_t vm = malloc(sizeof(struct vm));
  memset(vm, 0, sizeof(struct vm));

  memcpy(vm->program, program, sizeof(program));
  memcpy(vm->mem, vm_program, sizeof(vm_program));

  while (1) {
    uint16_t instr = (vm->program[vm->pc + 1] << 8) | vm->program[vm->pc];
    vm->pc += 2;
    uint8_t op = instr >> 12;
    if (op >= sizeof(handlers) / sizeof(handlers[0]))
      continue;

    handlers[op](vm, instr);
  }

  return 0;
}
